modLoader="javafml"
loaderVersion="[44,)"
license="MIT"
issueTrackerURL="https://github.com/anviaan/SculkHorn/issues"

[[mods]]
modId="sculkhornid"
version="1.2.0"
displayName="Sculk Horn Mod"
updateJSONURL="https://anvian-page.netlify.app/forge/sculkhornid.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sculk-horn"
logoFile="icon.png"
authors="anvian"
credits="PinhaColada2222"
description="Creates an area or distance sonic attack with 2 new horns."
displayTest="MATCH_VERSION"
[[dependencies.sculkhornid]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sculkhornid]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
